spring:
  application:
    name: Team14_BE

  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${USERNAME}
    url: ${URL}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}

  auth:
    token:
      url: ${KAKAO_AUTH_TOKEN_URL}

  user:
    api:
      url: ${KAKAO_USER_API_URL}

pg:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com

key:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

jwt:
  expire-time: 1

front:
  page:
    signup: ${FRONT_PAGE_SIGNUP}

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}